[server]
headless = true
port = 8501
enableCORS = true

[theme]
base = "dark"
primaryColor="#ff7e00"
backgroundColor="#3b3b3b"
secondaryBackgroundColor="#1c1c1c"
textColor="#ffffff"

[client]
showSidebarNavigation = false
